### ISSUE TITLE
app do not start

### ISSUE THREAD

**Issue by Feanarus** [krvi/XIV-Hunt#2]
### Which version, and executable, of XIV-Hunt together with which version of FFXIV have the issue you are about to describe?  
<sup>**For example:** *XIV-Huntx86.exe (v4.2.5.2) together with ffxiv.exe (DX9)*</sup>  
<sup>**Or:** *XIV-Hunt.exe (v4.2.5.2) together with ffxiv_dx11.exe (DX11)*</sup>  

---

XIV-Hunt.exe (v4.2.21.0) together with ffxiv_dx11.exe (DX11)

### What was the intended behaviour?

---

app start

### What was the actual behaviour?

---

app do not start since win 1803 update

### Steps to reliably reproduce the behaviour?

---

?

### If it concerns a hunt or F.A.T.E. report, on which world and time(incl. timezone) would the report have been made?

---

?

**Comment by krvi** [comment]
Thank you for the issue report.
I will try find the time to test it on Win10 (1803) in the next few days.
Do you have an `error.txt` in any of the following directories? Or perhaps their parent directory?
- `C:\Users\<user>\AppData\Local\XIVHunt\app-4.2.21`
- `C:\Users\<user>\AppData\Local\XIVHunt\app-4.2.22`

**Comment by vkhromenkov** [comment]
Had the same problem on Win10 1803, but only with Setup.exe.
So, had run compatibility wizard for it and OS recommended Win8.
It helped to run installer without issues.
After that app is starting without any problem, no error.txt anywhere

**Comment by krvi** [comment]
I just did a fresh install of Windows 10 (1803) and was unable to reproduce the issue using Setup.exe (4.2.22).

**Comment by Feanarus** [comment]
System.Configuration.ConfigurationErrorsException:Configuration system failed to initialize
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   at System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(InternalConfigEventArgs e)
   at System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(String configPath, BaseConfigurationRecord configRecord)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at FFXIV_GameSense.Properties.Settings.get_CallUpgrade()
   at FFXIV_GameSense.Program.Main(String[] args)

**Comment by krvi** [comment]
@Feanarus Thank you. The first error you posted seems to indicate that there was a problem in restoring the configuration file from a previous version.
If you want to _try_ to work around it, look for and delete all files and sub-directories in the following path:
- C:\Users\<user>\AppData\Local\FFXIV_GameSense\

_Make sure to copy/backup them if you want to **try** to restore them afterwards._ Though I believe that may reintroduce the issue.

Does the normal `C:\Users\<user>\AppData\Local\XIVHunt\app-4.2.22\XIV-Hunt.exe` work this way, with a clean/empty FFXIV_GameSense directory?
If it does, the issue is probably caused by a (corrupt?) config file.

**But**, seeing that you bypassed it by unpacking the app :+1: The 2nd error _just_ means that it lacks the auto-update functionality because `Update.exe` is not found in the parent directory of the running directory.

**Comment by Feanarus** [comment]
@krvi thank you for your support.

i deleted 
```
C:\Users\<user>\AppData\Local\FFXIV_GameSense
C:\Users\<user>\AppData\Local\XIVHunt
```
and run the setup.exe, the app starts and work fine, no problems anymore thank you so much!

**Comment by krvi** [comment]
Thank you. Whatever the cause, it should not happen again after (https://github.com/krvi/XIV-Hunt/commit/8a53758f0f77e4bc936de9bd8ddd847010865b59) 4.2.23.
